"""
This is a legacy settings file, do not change it!
"""
DEFAULT_CHART_COLORS = {
    "paper_0": "var(--kerykeion-chart-color-paper-0)",
    "paper_1": "var(--kerykeion-chart-color-paper-1)",
    "zodiac_bg_0": "var(--kerykeion-chart-color-zodiac-bg-0)",
    "zodiac_bg_1": "var(--kerykeion-chart-color-zodiac-bg-1)",
    "zodiac_bg_2": "var(--kerykeion-chart-color-zodiac-bg-2)",
    "zodiac_bg_3": "var(--kerykeion-chart-color-zodiac-bg-3)",
    "zodiac_bg_4": "var(--kerykeion-chart-color-zodiac-bg-4)",
    "zodiac_bg_5": "var(--kerykeion-chart-color-zodiac-bg-5)",
    "zodiac_bg_6": "var(--kerykeion-chart-color-zodiac-bg-6)",
    "zodiac_bg_7": "var(--kerykeion-chart-color-zodiac-bg-7)",
    "zodiac_bg_8": "var(--kerykeion-chart-color-zodiac-bg-8)",
    "zodiac_bg_9": "var(--kerykeion-chart-color-zodiac-bg-9)",
    "zodiac_bg_10": "var(--kerykeion-chart-color-zodiac-bg-10)",
    "zodiac_bg_11": "var(--kerykeion-chart-color-zodiac-bg-11)",
    "zodiac_icon_0": "var(--kerykeion-chart-color-zodiac-icon-0)",
    "zodiac_icon_1": "var(--kerykeion-chart-color-zodiac-icon-1)",
    "zodiac_icon_2": "var(--kerykeion-chart-color-zodiac-icon-2)",
    "zodiac_icon_3": "var(--kerykeion-chart-color-zodiac-icon-3)",
    "zodiac_icon_4": "var(--kerykeion-chart-color-zodiac-icon-4)",
    "zodiac_icon_5": "var(--kerykeion-chart-color-zodiac-icon-5)",
    "zodiac_icon_6": "var(--kerykeion-chart-color-zodiac-icon-6)",
    "zodiac_icon_7": "var(--kerykeion-chart-color-zodiac-icon-7)",
    "zodiac_icon_8": "var(--kerykeion-chart-color-zodiac-icon-8)",
    "zodiac_icon_9": "var(--kerykeion-chart-color-zodiac-icon-9)",
    "zodiac_icon_10": "var(--kerykeion-chart-color-zodiac-icon-10)",
    "zodiac_icon_11": "var(--kerykeion-chart-color-zodiac-icon-11)",
    "zodiac_radix_ring_0": "var(--kerykeion-chart-color-zodiac-radix-ring-0)",
    "zodiac_radix_ring_1": "var(--kerykeion-chart-color-zodiac-radix-ring-1)",
    "zodiac_radix_ring_2": "var(--kerykeion-chart-color-zodiac-radix-ring-2)",
    "zodiac_transit_ring_0": "var(--kerykeion-chart-color-zodiac-transit-ring-0)",
    "zodiac_transit_ring_1": "var(--kerykeion-chart-color-zodiac-transit-ring-1)",
    "zodiac_transit_ring_2": "var(--kerykeion-chart-color-zodiac-transit-ring-2)",
    "zodiac_transit_ring_3": "var(--kerykeion-chart-color-zodiac-transit-ring-3)",
    "houses_radix_line": "var(--kerykeion-chart-color-houses-radix-line)",
    "houses_transit_line": "var(--kerykeion-chart-color-houses-transit-line)",
    "lunar_phase_0": "var(--kerykeion-chart-color-lunar-phase-0)",
    "lunar_phase_1": "var(--kerykeion-chart-color-lunar-phase-1)",
}
