"""Glyph advance widths, measured — the data behind the info panel's row guard.

Generated by ``scripts/regenerate_glyph_widths.py`` from three reference fonts
and consumed by :func:`estimate_text_width` alone. It lives in its own module so
a re-measurement's diff lands here rather than inside the 5.6k-line renderer,
the same reason ``tests/data/glyph_advances.json`` is a data file rather than a
Python literal.

@module kerykeion.charts.glyph_metrics
"""

from __future__ import annotations


# What a glyph costs, as a fraction of the em.
#
# The panel's text nodes name no font-family, so the real glyphs are the
# viewer's choice and no exact width exists here. This table is the widest
# advance each character has across Times, Helvetica and Arial Unicode, rounded
# *up* to 1/50 em, so it reads at or above what those three will render and
# never below.
#
# A per-character table rather than an average, because the average is what got
# this wrong twice. Latin letters alone span 0.28em (i, l, t) to 0.89em (M, W) —
# a 3.2x range — so any single figure either undercharges the wide half or
# mangles ordinary names to protect against it. A first version charged 0.55em
# by default and listed only the characters above 0.80em as exceptions, which
# left 670 measured characters undercharged, lowercase `w` and Cyrillic `ж ю ы`
# among them: a Russian synastry overran the wheel by 21px, the same magnitude
# as the ideograph bug the table was written to fix.
#
# Devanagari is measured for the inverse reason: under the block ceiling every
# code point of a shipped Hindi row cost 1.04 em — matras and viramas included —
# which read the row at over twice its rendered width, and the trims that share
# this estimator amputated text that fit with a third of the slot to spare.
# Combining marks appear here at what the fonts' hmtx tables declare, most of
# them zero: shaping only stacks and fuses, never widens, so the figure is a
# measurement and still not an underestimate.
#
# Generated from the three fonts' `hmtx` tables; regenerate with
# `poe regenerate:glyph-widths` if the reference set ever changes.
_MEASURED_EM: dict[float, str] = {
    0.00: 'ँं़ुूृॄॅॆेै्॒॑॓॔ॢॣ',
    0.20: "'",
    0.24: 'ɉ‛',
    0.26: '|¦Ɩ',
    0.28: ' ,./:;\\ijlt\xa0·ìíîïĭįıĵĺļłţƫƭǀǐǰȉȋțȷͺ;·ΐίιϊϳіїјӏ',
    0.30: 'ः',
    0.32: 'ŧािीॉॊोौ',
    0.34: '!()-I[]`fr¡¨\xad²³´¸¹ÌÍÎÏĬĮİŕŗřſǃǏȈȊȑȓʹ͵΄ІЇ҃҅҆Ӏ।‐‑‘’‚‟․‧',
    0.36: 'ŀƗƚ΅•‣',
    0.38: 'ªºƪऽ॰',
    0.40: '°ĪīľɍΙΪ҄ґғ',
    0.42: '"гѓ',
    0.44: 'ĩťϯҟӄӷ‖',
    0.46: 'Ĩѯ“”„',
    0.48: '^{}ƺǁ',
    0.50: '*Jcksvxyz¯çýÿćĉċčĴķĸśŝşšŷźżžƙƨƶǩșȳȼͻͼͽζξτϲЈзстухѕўѵरऱ‗',
    0.52: 'ϩϵ϶эєҁҙқҫҭҳӟӡӭӯӱӳӿट॥',
    0.54: '¶ƹƽǮǯϧчьӌइईठढदढ़',
    0.56: '#$0123456789?_abdeghnopqu¢£¤¥§«»àáâãäåèéêëðñòóôõöùúûüþāăąđēĕėęěĝğġģĥħĳńņňŋōŏőũūŭůűųƀƃƄƅƌƒƛƞƥƼƾƿǉǎǒǔǖǘǚǜǝǟǡǧǫǭǵǹǻȁȃȅȇȍȏȕȗȟȧȩȫȭȯȱȽɁɂɇɈέγεκλνςχϥϨϸавекнопряёђћќџѳѻҐҕҷҹһәӛӵह‒–†‡',
    0.58: 'µƈƍƬƻǂϐϜϞϮϱЃГблцѐѝҒңҧҩӈӑӓӗӣӥӧөӫप',
    0.60: '+<=>~¬±×÷ǥийѧѷҞӃउगडतनऩबवग़ड़',
    0.62: 'FLTZ¿ßøĹĻĽĿŁŢŤŦŹŻŽƐƑƩƮƴƵǿȚȾɋɏΓΣάήΰαβδηθμορσυϋόύϑϫϬϭϰТдѣѫѮҝӠӶऍऎएऐयषय़',
    0.64: 'ŉƷƸϒϔϪъҬघङथम०१२३४५६७८९',
    0.66: 'ƔΊϕЬҔधस',
    0.68: 'BEPSÈÉÊËÞďĒĔĖĘĚŚŜŞŠƂƋƎƘơƧƲǷȄȆȘȜȝȨȺɅɆΞΡΤπϷЀЁЅБВЕЗРѦѴѶҘҡҰұӖӞӾऌकलक़ॡ‥',
    0.70: 'ưϠϤϦЧм҂ҽҿӋअचजञणफभशज़फ़',
    0.72: 'ϼДЛҥҵҶҸҺӴऊछझ',
    0.74: 'ACDHKNRUVXYwÀÁÂÃÄÅÇÐÑÙÚÛÜÝĀĂĄĆĈĊČĎĐĤĦĶŃŅŇŊŔŖŘŨŪŬŮŰŲŵŶŸƆƉƝƤƦǍǓǕǗǙǛǞǠǨǸǺȀȂȐȒȔȖȞȠȦȲȻɃΒΔΕΖφψϓϚϹϻϽϾϿЄЏАКНПСХЭЯыѥѱҀҚҦҪҮүҲӇӐӒӬखळऴख़',
    0.76: '©®ƁƏƱƳЌЍЎИЙУЦҢӂӘӚӢӤӮӰӲӹ',
    0.78: '&GOQÒÓÔÕÖØĜĞĠĢĲŌŎŐƇƟǌǑǦǪǬǴǾȌȎȪȬȮȰɎΚΛΝΥΧΩΫωώϴОжюѡѲѺѽѿҜҨ',
    0.80: 'ƊƓƣǤɌΆϖӦӨӪ',
    0.82: 'ƕшњѢѩѭ',
    0.84: 'm¼½¾ƜΑΗΘΟΠΦϣϺЪфщѪѰ',
    0.86: 'ɄɊФҗӝ',
    0.88: 'ƯϢЂЋљҠ',
    0.90: '%MæƠǈǣǽΨМӕॐ',
    0.92: 'ȹҼҾआऋऑऒओऔॠ',
    0.94: 'ȸЫҤҴӸ',
    0.96: 'WœŴΌΏΜШЩѨ',
    0.98: 'ѠѼѾӁ',
    1.00: 'ÆŒǋǢǼΈЖӔ—―…',
    1.02: '@ƢЊЮѤ',
    1.04: 'Ǉ',
    1.06: 'ǆǳΎѬ',
    1.08: 'ѹ',
    1.10: 'Ή',
    1.12: 'ЉҖӜ',
    1.24: 'ǅǊǲ',
    1.28: 'Ѹ',
    1.34: 'ǄǱ',
}

_MEASURED_EM_BY_CHAR: dict[str, float] = {char: em for em, chars in _MEASURED_EM.items() for char in chars}

# Anything outside the table above. Not a single fallback figure — that was
# tried twice and was wrong both times. `1.0` looked like a safe ceiling because
# ideographs are one em; 510 characters the reference fonts carry exceed it, up
# to 2.26 em among the Arabic presentation forms, so an Arabic name overran the
# wheel by 39px. What holds instead is a ceiling per 256-code-point block: the
# widest advance any character in that block has across the three fonts, rounded
# up. 147 of the 172 blocks come in at or under one em, so this costs almost
# nothing where the old figure happened to be right, and is correct where it was
# not.
#
# Combining marks in the measured ranges above are charged their measured
# advance like any other character — zero for most, the SOFT HYPHEN its real
# 0.34 em. A mark OUTSIDE those ranges still pays its block ceiling: an
# unmeasured script's renderer is a guess, and the guard may only guess high.
_BLOCK_CEILING_EM: tuple[tuple[int, int, float], ...] = (
    (0x0000, 0x00FF, 1.02),
    (0x0100, 0x01FF, 1.34),
    (0x0200, 0x02FF, 1.04),
    (0x0300, 0x03FF, 1.10),
    (0x0400, 0x04FF, 1.28),
    (0x0500, 0x05FF, 0.76),
    (0x0600, 0x06FF, 1.30),
    (0x0900, 0x09FF, 1.04),
    (0x0A00, 0x0AFF, 1.06),
    (0x0B00, 0x0BFF, 2.00),
    (0x0C00, 0x0CFF, 1.70),
    (0x0D00, 0x0DFF, 1.84),
    (0x0E00, 0x0EFF, 1.28),
    (0x0F00, 0x0FFF, 0.62),
    (0x1000, 0x10FF, 0.98),
    (0x1100, 0x11FF, 1.00),
    (0x1C00, 0x1CFF, 1.06),
    (0x1D00, 0x1DFF, 0.94),
    (0x1E00, 0x1EFF, 0.96),
    (0x1F00, 0x1FFF, 1.48),
    (0x2000, 0x20FF, 1.38),
    (0x2100, 0x21FF, 1.74),
    (0x2200, 0x22FF, 1.36),
    (0x2300, 0x23FF, 1.10),
    (0x2400, 0x25FF, 1.00),
    (0x2600, 0x26FF, 1.10),
    (0x2700, 0x27FF, 0.98),
    (0x2C00, 0x2CFF, 0.80),
    (0x2E00, 0x2EFF, 1.20),
    (0x3000, 0x33FF, 1.00),
    (0x4E00, 0x60FF, 1.00),
    (0x6100, 0x61FF, 1.02),
    (0x6200, 0x9FFF, 1.00),
    (0xA700, 0xA7FF, 0.68),
    (0xAC00, 0xD7FF, 1.00),
    (0xE800, 0xE8FF, 0.92),
    (0xF000, 0xF0FF, 0.50),
    (0xF700, 0xF7FF, 0.86),
    (0xF800, 0xF8FF, 0.80),
    (0xF900, 0xFAFF, 1.00),
    (0xFB00, 0xFBFF, 1.22),
    (0xFC00, 0xFCFF, 1.58),
    (0xFD00, 0xFDFF, 2.26),
    (0xFE00, 0xFEFF, 1.30),
    (0xFF00, 0xFFFF, 1.00),
)

#: For a character in no listed block. The widest advance in the whole covered
#: repertoire, so it cannot be an underestimate for any glyph these fonts carry.
_UNKNOWN_BLOCK_CEILING_EM: float = 2.26


def _block_ceiling(code_point: int) -> float:
    for low, high, ceiling in _BLOCK_CEILING_EM:
        if low <= code_point <= high:
            return ceiling
    return _UNKNOWN_BLOCK_CEILING_EM


def estimate_text_width(text: str, font_size: float = 10.0) -> float:
    """Rough rendered width of *text*, in pixels, for the info panel's rows.

    A character count cannot do this job, which is what the first version of the
    row-width guard tried: the same 38-character row measures 168px of Latin
    Helvetica and 250px of Arial Unicode ideographs.

    Exact for the scripts the panel's own text and the overwhelming majority of
    names are written in (see :data:`_MEASURED_EM`), and an upper bound
    everywhere else (see :data:`_BLOCK_CEILING_EM`). Never an underestimate for
    any character the reference fonts carry — which is the one property that
    matters, since the row it guards runs under the wheel graphics when it is
    wrong, and has done three times.
    """
    total = 0.0
    for char in text:
        measured = _MEASURED_EM_BY_CHAR.get(char)
        total += font_size * (measured if measured is not None else _block_ceiling(ord(char)))
    return total
