#!/usr/bin/env python3
"""
Reads the original Kerykeion chart.xml template and CSS theme files,
then generates a Dart source file containing them as string constants.

Usage:
    python tool/generate_chart_assets.py

Output:
    lib/src/charts/chart_assets.generated.dart
"""

import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DART_PKG_ROOT = os.path.dirname(SCRIPT_DIR)  # kerykeion/dart
KERYKEION_ROOT = os.path.dirname(DART_PKG_ROOT)  # kerykeion/

TEMPLATE_PATH = os.path.join(
    KERYKEION_ROOT, "kerykeion", "charts", "templates", "chart.xml"
)
THEMES_DIR = os.path.join(KERYKEION_ROOT, "kerykeion", "charts", "themes")
OUTPUT_PATH = os.path.join(
    DART_PKG_ROOT, "lib", "src", "charts", "chart_assets.generated.dart"
)

# All CSS theme files to bundle
THEME_FILES = [
    "classic.css",
    "dark.css",
    "dark-high-contrast.css",
    "light.css",
    "black-and-white.css",
    "strawberry.css",
]


def escape_dart_string(text: str) -> str:
    """Escape a raw string for embedding inside Dart triple-quoted raw string.

    We use a regular triple-quoted string (non-raw) so we can include
    all characters. We need to escape: backslash, dollar sign, and
    triple-quote sequences.
    """
    # Escape backslashes first
    text = text.replace("\\", "\\\\")
    # Escape dollar signs (Dart string interpolation)
    text = text.replace("$", "\\$")
    # Break any triple-quote sequences
    text = text.replace("'''", "'\\'\\''")
    return text


def convert_template_vars(text: str) -> str:
    """Convert Python $variable template markers to {{variable}} placeholders.

    Python's string.Template uses $var or ${var} syntax.
    We convert to {{var}} so Dart can do simple string replacement.
    """
    # Replace ${var} form first
    text = re.sub(r"\$\{(\w+)\}", r"{{\1}}", text)
    # Replace $var form (word boundary after var name)
    text = re.sub(r"\$(\w+)", r"{{\1}}", text)
    return text


def read_file(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def extract_template_variables(text: str) -> list[str]:
    """Extract all $variable names from the template."""
    vars_set = set()
    for m in re.finditer(r"\$\{?(\w+)\}?", text):
        vars_set.add(m.group(1))
    return sorted(vars_set)


def to_camel_case(name: str) -> str:
    """Convert snake_case or kebab-case to camelCase."""
    parts = name.replace("-", "_").split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def generate_dart_file():
    # ── Read template ──
    if not os.path.exists(TEMPLATE_PATH):
        print(f"ERROR: Template not found: {TEMPLATE_PATH}", file=sys.stderr)
        sys.exit(1)

    raw_template = read_file(TEMPLATE_PATH)
    template_vars = extract_template_variables(raw_template)

    # Convert $var → {{var}} then escape for Dart
    converted_template = convert_template_vars(raw_template)
    escaped_template = escape_dart_string(converted_template)

    # ── Read themes ──
    themes: dict[str, str] = {}
    for theme_file in THEME_FILES:
        theme_path = os.path.join(THEMES_DIR, theme_file)
        if os.path.exists(theme_path):
            theme_name = theme_file.replace(".css", "").replace("-", "_")
            themes[theme_name] = read_file(theme_path)
        else:
            print(f"WARNING: Theme not found: {theme_path}", file=sys.stderr)

    # ── Generate Dart ──
    lines = []
    lines.append("// GENERATED FILE — DO NOT EDIT BY HAND")
    lines.append("// Generated by tool/generate_chart_assets.py")
    lines.append(f"// Source template: {os.path.relpath(TEMPLATE_PATH, DART_PKG_ROOT)}")
    lines.append(f"// Source themes dir: {os.path.relpath(THEMES_DIR, DART_PKG_ROOT)}")
    lines.append("//")
    lines.append(f"// Template variables ({len(template_vars)}):")
    for v in template_vars:
        lines.append(f"//   {v}")
    lines.append("")
    lines.append("/// All template variable names used in the SVG chart template.")
    lines.append(f"const List<String> chartTemplateVariables = [")
    for v in template_vars:
        lines.append(f"  '{v}',")
    lines.append("];")
    lines.append("")

    # ── SVG template constant ──
    lines.append("/// The SVG chart template with {{variable}} placeholders.")
    lines.append("///")
    lines.append("/// Originally from kerykeion/charts/templates/chart.xml.")
    lines.append("/// Python \\$variable markers have been converted to {{variable}}.")
    lines.append("const String chartSvgTemplate = '''")
    lines.append(escaped_template)
    lines.append("''';")
    lines.append("")

    # ── Theme constants ──
    lines.append("/// Available chart theme names.")
    lines.append(f"const List<String> availableThemeNames = [")
    for name in themes:
        lines.append(f"  '{name}',")
    lines.append("];")
    lines.append("")

    lines.append("/// Map of theme name → CSS content.")
    lines.append("const Map<String, String> chartThemes = {")
    for name, css_content in themes.items():
        escaped_css = escape_dart_string(css_content)
        lines.append(f"  '{name}': '''")
        lines.append(escaped_css)
        lines.append("''',")
    lines.append("};")
    lines.append("")

    # ── Convenience getters ──
    for name in themes:
        const_name = f"chartTheme{to_camel_case(name).removeprefix(name.split('_')[0]).capitalize() if '_' in name else name.capitalize()}"
        # Simpler: just camelCase the whole thing
        const_name = "chartTheme" + "".join(p.capitalize() for p in name.split("_"))
        lines.append(f"/// CSS content for the '{name.replace('_', '-')}' theme.")
        lines.append(f"const String {const_name} = '''")
        escaped_css = escape_dart_string(themes[name])
        lines.append(escaped_css)
        lines.append("''';")
        lines.append("")

    # ── Helper function ──
    lines.append("/// Substitute all {{key}} placeholders in [template] with values from [vars].")
    lines.append("String substituteTemplate(String template, Map<String, String> vars) {")
    lines.append("  var result = template;")
    lines.append("  for (final entry in vars.entries) {")
    lines.append("    result = result.replaceAll('{{' + entry.key + '}}', entry.value);")
    lines.append("  }")
    lines.append("  return result;")
    lines.append("}")
    lines.append("")

    # ── Write output ──
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated: {OUTPUT_PATH}")
    print(f"  Template variables: {len(template_vars)}")
    print(f"  Themes bundled: {len(themes)}")
    print(f"  Output size: {os.path.getsize(OUTPUT_PATH):,} bytes")


if __name__ == "__main__":
    generate_dart_file()
