"""
Expected lunar return data for key subjects.

This file is auto-generated by scripts/regenerate_all.py
DO NOT EDIT MANUALLY - regenerate using: python scripts/regenerate_all.py --returns

Generated: 2026-02-11T20:06:21.011571
Total entries: 3
"""

EXPECTED_LUNAR_RETURNS = {
    "john_lennon_1940": {
        "returns": [
            {
                "iso_datetime": "2023-01-22T00:00:43+00:00",
                "julian_day": 2459966.5004976853,
                "moon_abs_pos": 303.54654630291316,
                "moon_sign": "Aqu",
            },
            {
                "iso_datetime": "2023-02-18T11:11:59+00:00",
                "julian_day": 2459993.966655093,
                "moon_abs_pos": 303.54649523060124,
                "moon_sign": "Aqu",
            },
            {
                "iso_datetime": "2023-03-17T20:14:15+00:00",
                "julian_day": 2460021.3432291667,
                "moon_abs_pos": 303.54657114678514,
                "moon_sign": "Aqu",
            },
            {
                "iso_datetime": "2023-04-14T02:40:30+00:00",
                "julian_day": 2460048.611458333,
                "moon_abs_pos": 303.54645162113593,
                "moon_sign": "Aqu",
            },
            {
                "iso_datetime": "2023-05-11T08:02:57+00:00",
                "julian_day": 2460075.8353819447,
                "moon_abs_pos": 303.546448368529,
                "moon_sign": "Aqu",
            },
            {
                "iso_datetime": "2023-06-07T14:30:04+00:00",
                "julian_day": 2460103.104212963,
                "moon_abs_pos": 303.5465000785983,
                "moon_sign": "Aqu",
            },
            {
                "iso_datetime": "2023-07-04T23:08:43+00:00",
                "julian_day": 2460130.464386574,
                "moon_abs_pos": 303.5465385308323,
                "moon_sign": "Aqu",
            },
            {
                "iso_datetime": "2023-08-01T09:32:53+00:00",
                "julian_day": 2460157.897835648,
                "moon_abs_pos": 303.5465549415493,
                "moon_sign": "Aqu",
            },
            {
                "iso_datetime": "2023-09-25T05:21:35+00:00",
                "julian_day": 2460212.723321759,
                "moon_abs_pos": 303.54657143929364,
                "moon_sign": "Aqu",
            },
            {
                "iso_datetime": "2023-10-22T12:08:43+00:00",
                "julian_day": 2460240.006053241,
                "moon_abs_pos": 303.54645825396904,
                "moon_sign": "Aqu",
            },
            {
                "iso_datetime": "2023-11-18T17:30:59+00:00",
                "julian_day": 2460267.229849537,
                "moon_abs_pos": 303.54656024885526,
                "moon_sign": "Aqu",
            },
            {
                "iso_datetime": "2023-12-15T23:50:20+00:00",
                "julian_day": 2460294.493287037,
                "moon_abs_pos": 303.5464762415515,
                "moon_sign": "Aqu",
            },
        ]
    },
    "johnny_depp_1963": {
        "returns": [
            {
                "iso_datetime": "2023-01-20T09:07:18+00:00",
                "julian_day": 2459964.8800694444,
                "moon_abs_pos": 278.7401007322888,
                "moon_sign": "Cap",
            },
            {
                "iso_datetime": "2023-02-16T19:23:23+00:00",
                "julian_day": 2459992.3079050924,
                "moon_abs_pos": 278.7401835895505,
                "moon_sign": "Cap",
            },
            {
                "iso_datetime": "2023-03-16T02:58:55+00:00",
                "julian_day": 2460019.624247685,
                "moon_abs_pos": 278.74016793025714,
                "moon_sign": "Cap",
            },
            {
                "iso_datetime": "2023-04-12T08:35:04+00:00",
                "julian_day": 2460046.857685185,
                "moon_abs_pos": 278.7400816819103,
                "moon_sign": "Cap",
            },
            {
                "iso_datetime": "2023-05-09T14:19:21+00:00",
                "julian_day": 2460074.0967708332,
                "moon_abs_pos": 278.74007609509266,
                "moon_sign": "Cap",
            },
            {
                "iso_datetime": "2023-06-05T21:53:51+00:00",
                "julian_day": 2460101.4123958335,
                "moon_abs_pos": 278.7400285048192,
                "moon_sign": "Cap",
            },
            {
                "iso_datetime": "2023-07-03T07:30:14+00:00",
                "julian_day": 2460128.812662037,
                "moon_abs_pos": 278.74017814817404,
                "moon_sign": "Cap",
            },
            {
                "iso_datetime": "2023-08-27T03:48:26+00:00",
                "julian_day": 2460183.6586342594,
                "moon_abs_pos": 278.7400616502087,
                "moon_sign": "Cap",
            },
            {
                "iso_datetime": "2023-09-23T11:32:42+00:00",
                "julian_day": 2460210.9810416666,
                "moon_abs_pos": 278.7400754439503,
                "moon_sign": "Cap",
            },
            {
                "iso_datetime": "2023-10-20T17:19:29+00:00",
                "julian_day": 2460238.221863426,
                "moon_abs_pos": 278.7400552399345,
                "moon_sign": "Cap",
            },
            {
                "iso_datetime": "2023-11-16T22:53:32+00:00",
                "julian_day": 2460265.4538425924,
                "moon_abs_pos": 278.74011477973954,
                "moon_sign": "Cap",
            },
            {
                "iso_datetime": "2023-12-14T06:20:13+00:00",
                "julian_day": 2460292.764039352,
                "moon_abs_pos": 278.740135171775,
                "moon_sign": "Cap",
            },
        ]
    },
    "paul_mccartney_1942": {
        "returns": [
            {
                "iso_datetime": "2023-01-09T15:27:26+00:00",
                "julian_day": 2459954.144050926,
                "moon_abs_pos": 138.2002165002823,
                "moon_sign": "Leo",
            },
            {
                "iso_datetime": "2023-02-05T21:32:18+00:00",
                "julian_day": 2459981.3974305554,
                "moon_abs_pos": 138.20017720681028,
                "moon_sign": "Leo",
            },
            {
                "iso_datetime": "2023-03-05T04:00:28+00:00",
                "julian_day": 2460008.6669907407,
                "moon_abs_pos": 138.20021757292164,
                "moon_sign": "Leo",
            },
            {
                "iso_datetime": "2023-04-01T11:17:24+00:00",
                "julian_day": 2460035.9704166665,
                "moon_abs_pos": 138.20018991351236,
                "moon_sign": "Leo",
            },
            {
                "iso_datetime": "2023-05-26T03:14:23+00:00",
                "julian_day": 2460090.6349884258,
                "moon_abs_pos": 138.20014391757363,
                "moon_sign": "Leo",
            },
            {
                "iso_datetime": "2023-06-22T10:41:16+00:00",
                "julian_day": 2460117.945324074,
                "moon_abs_pos": 138.2001175459146,
                "moon_sign": "Leo",
            },
            {
                "iso_datetime": "2023-07-19T17:18:16+00:00",
                "julian_day": 2460145.2210185183,
                "moon_abs_pos": 138.2000906669394,
                "moon_sign": "Leo",
            },
            {
                "iso_datetime": "2023-08-15T23:20:12+00:00",
                "julian_day": 2460172.472361111,
                "moon_abs_pos": 138.20009143871965,
                "moon_sign": "Leo",
            },
            {
                "iso_datetime": "2023-09-12T05:23:38+00:00",
                "julian_day": 2460199.7247453704,
                "moon_abs_pos": 138.2002021875534,
                "moon_sign": "Leo",
            },
            {
                "iso_datetime": "2023-10-09T12:06:50+00:00",
                "julian_day": 2460227.0047453702,
                "moon_abs_pos": 138.2000941423233,
                "moon_sign": "Leo",
            },
            {
                "iso_datetime": "2023-11-05T19:46:15+00:00",
                "julian_day": 2460254.323784722,
                "moon_abs_pos": 138.2001987168468,
                "moon_sign": "Leo",
            },
            {
                "iso_datetime": "2023-12-03T04:03:38+00:00",
                "julian_day": 2460281.669189815,
                "moon_abs_pos": 138.20009925726433,
                "moon_sign": "Leo",
            },
        ]
    },
}
