"""
Parametrized tests for house cusp positions.

This module tests that house cusp positions match expected values across:
- Multiple time periods (100 AD to 2200 AD)
- Multiple geographic locations
- All 12 house cusps

Tests are data-driven using expected_positions.py as the baseline.
"""

import pytest
from pytest import approx
from typing import Dict, Any

from kerykeion import AstrologicalSubjectFactory

from tests.data.test_subjects_matrix import (
    TEMPORAL_SUBJECTS,
    GEOGRAPHIC_SUBJECTS,
    HOUSES,
    HOUSE_SYSTEMS,
    get_subject_by_id,
)

# Import expected data - will be generated by regenerate_all.py
try:
    from tests.data.expected_positions import EXPECTED_POSITIONS
except ImportError:
    EXPECTED_POSITIONS = {}
    pytest.skip(
        "Expected positions not generated. Run: python scripts/regenerate_all.py --positions", allow_module_level=True
    )


# =============================================================================
# FIXTURES
# =============================================================================

# Filter out subjects that don't have expected data
VALID_TEMPORAL_IDS = [s["id"] for s in TEMPORAL_SUBJECTS if s["id"] in EXPECTED_POSITIONS]
VALID_GEOGRAPHIC_IDS = [s["id"] for s in GEOGRAPHIC_SUBJECTS if s["id"] in EXPECTED_POSITIONS]


@pytest.fixture(params=VALID_TEMPORAL_IDS)
def temporal_subject_id(request) -> str:
    """Parametrized fixture for temporal subject IDs with expected data."""
    return request.param


@pytest.fixture(params=VALID_GEOGRAPHIC_IDS)
def geographic_subject_id(request) -> str:
    """Parametrized fixture for geographic subject IDs with expected data."""
    return request.param


@pytest.fixture(params=HOUSES)
def house(request) -> str:
    """Parametrized fixture for all 12 houses."""
    return request.param


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def create_subject_from_id(subject_id: str, house_system: str = "P"):
    """Create an astrological subject from its ID in the test matrix."""
    # Check temporal subjects first
    for data in TEMPORAL_SUBJECTS:
        if data["id"] == subject_id:
            return AstrologicalSubjectFactory.from_birth_data(
                name=data["name"],
                year=data["year"],
                month=data["month"],
                day=data["day"],
                hour=data["hour"],
                minute=data["minute"],
                lat=data["lat"],
                lng=data["lng"],
                tz_str=data["tz_str"],
                online=False,
                suppress_geonames_warning=True,
                houses_system_identifier=house_system,
            )

    # Check geographic subjects
    for data in GEOGRAPHIC_SUBJECTS:
        if data["id"] == subject_id:
            return AstrologicalSubjectFactory.from_birth_data(
                name=f"Test_{data['id']}",
                year=1990,
                month=6,
                day=15,
                hour=12,
                minute=0,
                lat=data["lat"],
                lng=data["lng"],
                tz_str=data["tz_str"],
                online=False,
                suppress_geonames_warning=True,
                houses_system_identifier=house_system,
            )

    raise ValueError(f"Subject ID '{subject_id}' not found in test matrix")


# =============================================================================
# TOLERANCE CONSTANTS
# =============================================================================

POSITION_ABS_TOL = 1e-2  # 0.01 degrees (36 arcseconds)


# =============================================================================
# PARAMETRIZED TESTS - TEMPORAL SUBJECTS x HOUSES
# =============================================================================


class TestTemporalHousePositions:
    """
    Test house cusp positions across different time periods.

    These tests validate that house cusp calculations produce consistent
    results for subjects from 100 AD through 2200 AD.
    """

    def test_house_abs_pos(self, temporal_subject_id: str, house: str):
        """Test absolute position (0-360) for each house cusp."""
        expected = EXPECTED_POSITIONS.get(temporal_subject_id, {})
        house_data = expected.get("houses", {}).get(house, {})

        if not house_data:
            pytest.skip(f"No expected data for {house} in {temporal_subject_id}")

        subject = create_subject_from_id(temporal_subject_id)
        actual_house = getattr(subject, house)

        assert actual_house.abs_pos == approx(house_data["abs_pos"], abs=POSITION_ABS_TOL), (
            f"{temporal_subject_id}/{house}: abs_pos mismatch"
        )

    def test_house_position(self, temporal_subject_id: str, house: str):
        """Test position within sign (0-30) for each house cusp."""
        expected = EXPECTED_POSITIONS.get(temporal_subject_id, {})
        house_data = expected.get("houses", {}).get(house, {})

        if not house_data:
            pytest.skip(f"No expected data for {house} in {temporal_subject_id}")

        subject = create_subject_from_id(temporal_subject_id)
        actual_house = getattr(subject, house)

        assert actual_house.position == approx(house_data["position"], abs=POSITION_ABS_TOL), (
            f"{temporal_subject_id}/{house}: position mismatch"
        )

    def test_house_sign(self, temporal_subject_id: str, house: str):
        """Test zodiac sign for each house cusp."""
        expected = EXPECTED_POSITIONS.get(temporal_subject_id, {})
        house_data = expected.get("houses", {}).get(house, {})

        if not house_data:
            pytest.skip(f"No expected data for {house} in {temporal_subject_id}")

        subject = create_subject_from_id(temporal_subject_id)
        actual_house = getattr(subject, house)

        assert actual_house.sign == house_data["sign"], (
            f"{temporal_subject_id}/{house}: sign mismatch - got {actual_house.sign}, expected {house_data['sign']}"
        )

    def test_house_sign_num(self, temporal_subject_id: str, house: str):
        """Test sign number (0-11) for each house cusp."""
        expected = EXPECTED_POSITIONS.get(temporal_subject_id, {})
        house_data = expected.get("houses", {}).get(house, {})

        if not house_data:
            pytest.skip(f"No expected data for {house} in {temporal_subject_id}")

        subject = create_subject_from_id(temporal_subject_id)
        actual_house = getattr(subject, house)

        assert actual_house.sign_num == house_data["sign_num"], f"{temporal_subject_id}/{house}: sign_num mismatch"

    def test_house_element(self, temporal_subject_id: str, house: str):
        """Test element for each house cusp."""
        expected = EXPECTED_POSITIONS.get(temporal_subject_id, {})
        house_data = expected.get("houses", {}).get(house, {})

        if not house_data:
            pytest.skip(f"No expected data for {house} in {temporal_subject_id}")

        subject = create_subject_from_id(temporal_subject_id)
        actual_house = getattr(subject, house)

        assert actual_house.element == house_data["element"], f"{temporal_subject_id}/{house}: element mismatch"

    def test_house_quality(self, temporal_subject_id: str, house: str):
        """Test quality/modality for each house cusp."""
        expected = EXPECTED_POSITIONS.get(temporal_subject_id, {})
        house_data = expected.get("houses", {}).get(house, {})

        if not house_data:
            pytest.skip(f"No expected data for {house} in {temporal_subject_id}")

        subject = create_subject_from_id(temporal_subject_id)
        actual_house = getattr(subject, house)

        assert actual_house.quality == house_data["quality"], f"{temporal_subject_id}/{house}: quality mismatch"


class TestGeographicHousePositions:
    """
    Test house cusp positions across different geographic locations.

    These tests validate that house cusp calculations are consistent across
    various latitudes and longitudes, including edge cases like polar regions.
    """

    def test_house_abs_pos(self, geographic_subject_id: str, house: str):
        """Test absolute position for each house cusp at different locations."""
        expected = EXPECTED_POSITIONS.get(geographic_subject_id, {})
        house_data = expected.get("houses", {}).get(house, {})

        if not house_data:
            pytest.skip(f"No expected data for {house} in {geographic_subject_id}")

        subject = create_subject_from_id(geographic_subject_id)
        actual_house = getattr(subject, house)

        assert actual_house.abs_pos == approx(house_data["abs_pos"], abs=POSITION_ABS_TOL), (
            f"{geographic_subject_id}/{house}: abs_pos mismatch"
        )

    def test_house_sign(self, geographic_subject_id: str, house: str):
        """Test zodiac sign for each house cusp at different locations."""
        expected = EXPECTED_POSITIONS.get(geographic_subject_id, {})
        house_data = expected.get("houses", {}).get(house, {})

        if not house_data:
            pytest.skip(f"No expected data for {house} in {geographic_subject_id}")

        subject = create_subject_from_id(geographic_subject_id)
        actual_house = getattr(subject, house)

        assert actual_house.sign == house_data["sign"], f"{geographic_subject_id}/{house}: sign mismatch"


# =============================================================================
# HOUSE SYSTEM TESTS
# =============================================================================


class TestHouseSystemVariations:
    """
    Test that different house systems produce different results.

    These tests validate that house system selection properly affects
    house cusp calculations.
    """

    @pytest.mark.parametrize("house_system", HOUSE_SYSTEMS[:5])  # Test first 5 systems
    def test_house_systems_differ(self, house_system: str):
        """Test that different house systems produce different house cusps."""
        # Use John Lennon as reference
        subject = AstrologicalSubjectFactory.from_birth_data(
            "John Lennon",
            1940,
            10,
            9,
            18,
            30,
            lat=53.4084,
            lng=-2.9916,
            tz_str="Europe/London",
            online=False,
            suppress_geonames_warning=True,
            houses_system_identifier=house_system,
        )

        # Verify house cusps are calculated
        assert subject.first_house is not None
        assert subject.first_house.abs_pos is not None
        assert 0 <= subject.first_house.abs_pos < 360

    def test_placidus_vs_whole_sign(self):
        """Test that Placidus and Whole Sign produce different house cusps."""
        placidus = AstrologicalSubjectFactory.from_birth_data(
            "John Lennon Placidus",
            1940,
            10,
            9,
            18,
            30,
            lat=53.4084,
            lng=-2.9916,
            tz_str="Europe/London",
            online=False,
            suppress_geonames_warning=True,
            houses_system_identifier="P",
        )

        whole_sign = AstrologicalSubjectFactory.from_birth_data(
            "John Lennon Whole Sign",
            1940,
            10,
            9,
            18,
            30,
            lat=53.4084,
            lng=-2.9916,
            tz_str="Europe/London",
            online=False,
            suppress_geonames_warning=True,
            houses_system_identifier="W",
        )

        # In Whole Sign, cusps are at 0° of each sign, not aligned with Ascendant
        # So first house cusp should be at 0° of Ascendant's sign
        asc_sign_num = placidus.ascendant.sign_num
        expected_whole_sign_first = asc_sign_num * 30.0

        # Verify Whole Sign starts at 0° of the sign
        assert whole_sign.first_house.abs_pos == approx(expected_whole_sign_first, abs=0.1), (
            f"Whole Sign first house should be at {expected_whole_sign_first}°"
        )

        # Verify Placidus has Ascendant at exact degree within sign
        assert placidus.first_house.abs_pos != approx(expected_whole_sign_first, abs=0.1), (
            "Placidus first house should differ from Whole Sign"
        )


# =============================================================================
# ANGULAR HOUSE CONSISTENCY TESTS
# =============================================================================


class TestAngularHouseConsistency:
    """
    Test consistency between angular houses and angles.

    The 1st house cusp should match Ascendant, 4th should match IC,
    7th should match Descendant, and 10th should match MC.
    """

    @pytest.mark.parametrize("subject_id", ["john_lennon_1940", "johnny_depp_1963", "paul_mccartney_1942"])
    def test_first_house_matches_ascendant(self, subject_id: str):
        """Test that 1st house cusp matches Ascendant."""
        subject = create_subject_from_id(subject_id)

        assert subject.first_house.abs_pos == approx(subject.ascendant.abs_pos, abs=1e-6), (
            f"{subject_id}: First house cusp should match Ascendant"
        )

    @pytest.mark.parametrize("subject_id", ["john_lennon_1940", "johnny_depp_1963", "paul_mccartney_1942"])
    def test_fourth_house_matches_ic(self, subject_id: str):
        """Test that 4th house cusp matches IC."""
        subject = create_subject_from_id(subject_id)

        assert subject.fourth_house.abs_pos == approx(subject.imum_coeli.abs_pos, abs=1e-6), (
            f"{subject_id}: Fourth house cusp should match IC"
        )

    @pytest.mark.parametrize("subject_id", ["john_lennon_1940", "johnny_depp_1963", "paul_mccartney_1942"])
    def test_seventh_house_matches_descendant(self, subject_id: str):
        """Test that 7th house cusp matches Descendant."""
        subject = create_subject_from_id(subject_id)

        assert subject.seventh_house.abs_pos == approx(subject.descendant.abs_pos, abs=1e-6), (
            f"{subject_id}: Seventh house cusp should match Descendant"
        )

    @pytest.mark.parametrize("subject_id", ["john_lennon_1940", "johnny_depp_1963", "paul_mccartney_1942"])
    def test_tenth_house_matches_mc(self, subject_id: str):
        """Test that 10th house cusp matches MC."""
        subject = create_subject_from_id(subject_id)

        assert subject.tenth_house.abs_pos == approx(subject.medium_coeli.abs_pos, abs=1e-6), (
            f"{subject_id}: Tenth house cusp should match MC"
        )


# =============================================================================
# INTEGRATION TESTS - ALL HOUSES FOR KEY SUBJECTS
# =============================================================================


class TestKeySubjectsHousesComplete:
    """
    Comprehensive tests for primary test subjects.

    These tests validate all house cusps for John Lennon, Johnny Depp,
    and Paul McCartney to ensure complete backward compatibility.
    """

    @pytest.mark.parametrize("subject_id", ["john_lennon_1940", "johnny_depp_1963", "paul_mccartney_1942"])
    def test_all_houses(self, subject_id: str):
        """Test all house cusp positions for key subjects."""
        expected = EXPECTED_POSITIONS.get(subject_id, {})

        if not expected:
            pytest.skip(f"No expected data for {subject_id}")

        subject = create_subject_from_id(subject_id)

        for house in HOUSES:
            house_data = expected.get("houses", {}).get(house, {})
            if house_data:
                actual_house = getattr(subject, house)
                assert actual_house.abs_pos == approx(house_data["abs_pos"], abs=POSITION_ABS_TOL), (
                    f"{subject_id}/{house} abs_pos"
                )
                assert actual_house.sign == house_data["sign"], f"{subject_id}/{house} sign"

    @pytest.mark.parametrize("subject_id", ["john_lennon_1940", "johnny_depp_1963", "paul_mccartney_1942"])
    def test_house_order(self, subject_id: str):
        """Test that house cusps are in ascending order (with wrap-around)."""
        subject = create_subject_from_id(subject_id)

        house_positions = [
            subject.first_house.abs_pos,
            subject.second_house.abs_pos,
            subject.third_house.abs_pos,
            subject.fourth_house.abs_pos,
            subject.fifth_house.abs_pos,
            subject.sixth_house.abs_pos,
            subject.seventh_house.abs_pos,
            subject.eighth_house.abs_pos,
            subject.ninth_house.abs_pos,
            subject.tenth_house.abs_pos,
            subject.eleventh_house.abs_pos,
            subject.twelfth_house.abs_pos,
        ]

        # Check that positions increase (with wrap-around at 360)
        for i in range(len(house_positions) - 1):
            current = house_positions[i]
            next_pos = house_positions[i + 1]

            # Handle wrap-around at 360
            if next_pos < current:
                next_pos += 360

            assert next_pos > current, (
                f"{subject_id}: House {i + 1} ({current}) should come before House {i + 2} ({house_positions[i + 1]})"
            )
