# -*- coding: utf-8 -*-
"""
Utilities

Shared helpers used across the library: zodiac and house lookups, Julian-day
and ISO date conversion, timezone resolution, angle arithmetic, moon-phase
naming and formatting.

This __init__ is a FLAT FACADE, unlike every other package here: it re-exports
the whole module surface, semi-private names included. That is deliberate.
`kerykeion.utilities` has 44 internal consumers and is imported by name (never
by module path) throughout the tests, so keeping the namespace flat means the
move costs zero call sites outside the package. Modules inside kerykeion import
from `.core` directly, which keeps the import graph exactly the shape it had --
the lazy imports breaking the utilities <-> ephemeris_backend cycle still break
the same cycle. The semi-private names below are re-exported because other
modules genuinely import them: `_POLAR_LATITUDE_LIMIT` by the ephemeris backend,
`_ZODIAC_SIGNS` by midpoints and solar arc.
"""

from .core import (
    CRITICAL,
    DEBUG,
    ERROR,
    HOUSE_FIELD_NAMES,
    INFO,
    TERRESTRIAL_PERSPECTIVES,
    WARNING,
    _ANCIENT_ISO_RE,
    _CSS_VARIABLE_PATTERN,
    _DAYS_IN_MONTH,
    _GREGORIAN_CE_EPOCH_JD,
    _HOUSE_NAMES,
    _HOUSE_NAMES_TUPLE,
    _HOUSE_NUMBERS,
    _LUNAR_PHASE_EMOJIS,
    _LUNAR_PHASE_NAMES,
    _POINT_NUMBER_MAP,
    _POLAR_LATITUDE_LIMIT,
    _PRE_DAYLIGHT_SAVING_HORIZON,
    _XML_ILLEGAL_CONTROL_CHARS,
    _XML_ILLEGAL_TRANSLATION,
    _ZODIAC_SIGNS,
    _assemble_ancient_iso,
    _days_in_proleptic_julian_month,
    _fold_offsets,
    _get_lunar_phase_index,
    _next_proleptic_julian_day,
    _split_decimal_hour_with_carry,
    _zone_label,
    angle_house_identities,
    calculate_moon_phase,
    check_and_adjust_polar_latitude,
    circular_mean,
    circular_sort,
    civil_jd,
    civil_leap_year,
    coincident_cusp_groups,
    datetime_to_julian,
    distribute_percentages_to_100,
    extract_year_from_iso,
    find_common_active_points,
    format_ancient_iso,
    format_astronomical_iso_date,
    format_degrees_below_bound,
    format_iso_display,
    format_timedelta_hhmm,
    get_available_astrological_points_list,
    get_house_name,
    get_house_number,
    get_houses_list,
    get_kerykeion_point_from_degree,
    get_moon_emoji_from_phase_int,
    get_moon_phase_name_from_phase_int,
    get_number_from_name,
    get_planet_house,
    has_terrestrial_frame,
    house_spans,
    inline_css_variables_in_svg,
    is_ambiguous,
    is_nonexistent,
    is_point_between,
    jd_to_iso_date,
    jd_to_iso_datetime,
    julian_to_datetime,
    localize_naive,
    logger,
    normalize_degree,
    normalize_longitude,
    normalize_zodiac_type,
    parse_astronomical_iso_moment,
    require_same_frame,
    resolve_sect_is_diurnal,
    resolve_subject_birth_datetime,
    resolve_subject_local_moment,
    resolve_subject_local_now,
    safe_timezone,
    setup_logging,
    strip_illegal_control_chars,
    validate_latitude,
    validate_longitude,
    wrap_180,
)

__all__ = [
    "HOUSE_FIELD_NAMES",
    "TERRESTRIAL_PERSPECTIVES",
    "angle_house_identities",
    "calculate_moon_phase",
    "check_and_adjust_polar_latitude",
    "circular_mean",
    "circular_sort",
    "civil_jd",
    "civil_leap_year",
    "coincident_cusp_groups",
    "datetime_to_julian",
    "distribute_percentages_to_100",
    "extract_year_from_iso",
    "find_common_active_points",
    "format_ancient_iso",
    "format_astronomical_iso_date",
    "format_degrees_below_bound",
    "format_iso_display",
    "format_timedelta_hhmm",
    "get_available_astrological_points_list",
    "get_house_name",
    "get_house_number",
    "get_houses_list",
    "get_kerykeion_point_from_degree",
    "get_moon_emoji_from_phase_int",
    "get_moon_phase_name_from_phase_int",
    "get_number_from_name",
    "get_planet_house",
    "has_terrestrial_frame",
    "house_spans",
    "inline_css_variables_in_svg",
    "is_ambiguous",
    "is_nonexistent",
    "is_point_between",
    "jd_to_iso_date",
    "jd_to_iso_datetime",
    "julian_to_datetime",
    "localize_naive",
    "normalize_degree",
    "normalize_longitude",
    "normalize_zodiac_type",
    "parse_astronomical_iso_moment",
    "require_same_frame",
    "resolve_sect_is_diurnal",
    "resolve_subject_birth_datetime",
    "resolve_subject_local_moment",
    "resolve_subject_local_now",
    "safe_timezone",
    "setup_logging",
    "strip_illegal_control_chars",
    "validate_latitude",
    "validate_longitude",
    "wrap_180",
]
