"""
Tests for the MoonPhaseOverviewModel report generated by ReportGenerator.

Covers:
- Golden snapshot regression against fixture file
- Required sections present in generated report
- Content formatting validation (percentages, degrees, dates)
- print_report() consistency with generate_report()
- Edge cases: missing optional fields, minimal model
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from kerykeion import (
    AstrologicalSubjectFactory,
    MoonPhaseDetailsFactory,
    ReportGenerator,
)
from kerykeion.schemas.kr_models import (
    MoonPhaseOverviewModel,
    MoonPhaseMoonSummaryModel,
    MoonPhaseSunInfoModel,
    MoonPhaseLocationModel,
)


FIXTURES_DIR = Path("tests/fixtures")

# -----------------------------------------------------------------------
# Required section titles in a full moon phase overview report
# -----------------------------------------------------------------------
_MOON_OVERVIEW_SECTIONS = [
    "Moon Summary",
    "Illumination Details",
    "Upcoming Phases",
    "Next Lunar Eclipse",
    "Sun Info",
    "Next Solar Eclipse",
    "Location",
]


# -----------------------------------------------------------------------
# Helper: deterministic subject for snapshot tests
# -----------------------------------------------------------------------
def _make_overview() -> MoonPhaseOverviewModel:
    """Create the same overview used to generate the golden fixture."""
    subject = AstrologicalSubjectFactory.from_birth_data(
        "Moon Phase Test",
        1993,
        10,
        10,
        12,
        12,
        lng=-0.1276,
        lat=51.5074,
        tz_str="Europe/London",
        online=False,
    )
    return MoonPhaseDetailsFactory.from_subject(subject)


# =====================================================================
# 1. Golden snapshot regression
# =====================================================================


class TestMoonPhaseOverviewSnapshot:
    """Verify report output matches the committed fixture file."""

    def test_snapshot_exact_match(self, capsys) -> None:
        overview = _make_overview()
        ReportGenerator(overview).print_report()
        captured = capsys.readouterr().out

        expected = (FIXTURES_DIR / "moon_phase_overview_report.txt").read_text(encoding="utf-8")
        assert captured == expected + "\n"

    def test_generate_matches_print(self) -> None:
        """generate_report() and print_report() must produce identical content."""
        overview = _make_overview()
        report = ReportGenerator(overview)
        generated = report.generate_report()

        expected = (FIXTURES_DIR / "moon_phase_overview_report.txt").read_text(encoding="utf-8")
        assert generated == expected


# =====================================================================
# 2. Section presence
# =====================================================================


class TestMoonPhaseOverviewSections:
    """All expected sections must appear in a full report."""

    @pytest.fixture(autouse=True)
    def _setup(self) -> None:
        self.text = ReportGenerator(_make_overview()).generate_report()

    @pytest.mark.parametrize("section", _MOON_OVERVIEW_SECTIONS)
    def test_section_present(self, section: str) -> None:
        assert section in self.text, f"Missing section: {section!r}"

    def test_title_contains_datestamp(self) -> None:
        assert "Moon Phase Overview" in self.text
        # RFC-2822-like datestamp in title
        assert "1993" in self.text


# =====================================================================
# 3. Content formatting validation
# =====================================================================


class TestMoonPhaseOverviewFormatting:
    """Validate numeric / date formatting in the report."""

    @pytest.fixture(autouse=True)
    def _setup(self) -> None:
        self.text = ReportGenerator(_make_overview()).generate_report()

    def test_illumination_percentage_format(self) -> None:
        """Illumination percentage is shown as 'NN%'."""
        assert re.search(r"\d+%", self.text), "No illumination percentage found"

    def test_visible_fraction_format(self) -> None:
        """Visible fraction uses 4 decimal places."""
        assert re.search(r"\d+\.\d{4}", self.text), "No 4-decimal fraction found"

    def test_phase_angle_format(self) -> None:
        """Phase angle uses 2 decimal places with degree symbol."""
        assert re.search(r"\d+\.\d{2}\xb0", self.text), "No phase angle with degree symbol"

    def test_sun_altitude_format(self) -> None:
        """Sun altitude uses 2 decimal places with degree symbol."""
        assert re.search(r"Sun Altitude.*\d+\.\d{2}\xb0", self.text)

    def test_upcoming_phases_has_four_rows(self) -> None:
        """Upcoming Phases table must list all 4 major phases."""
        for phase in ["New Moon", "First Quarter", "Full Moon", "Last Quarter"]:
            assert phase in self.text, f"Missing phase: {phase!r}"

    def test_eclipse_date_format(self) -> None:
        """Eclipse dates use RFC-2822-like format."""
        # e.g. "Mon, 29 Nov 1993 06:26:06 +0000"
        assert re.search(
            r"\w{3}, \d{2} \w{3} \d{4} \d{2}:\d{2}:\d{2} \+\d{4}",
            self.text,
        ), "No RFC-2822 date found in eclipse section"


# =====================================================================
# 4. Edge cases: minimal model (only required fields)
# =====================================================================


class TestMoonPhaseOverviewMinimalModel:
    """Report handles a MoonPhaseOverviewModel with only required fields."""

    def test_minimal_model_no_crash(self) -> None:
        """A model with no optional fields should still produce a valid report."""
        minimal = MoonPhaseOverviewModel(
            timestamp=0,
            datestamp="Thu, 01 Jan 1970 00:00:00 +0000",
            moon=MoonPhaseMoonSummaryModel(),
        )
        text = ReportGenerator(minimal).generate_report()
        assert "Moon Phase Overview" in text
        # No optional sections should appear
        assert "Sun Info" not in text
        assert "Location" not in text

    def test_minimal_model_with_moon_summary(self) -> None:
        """A model with only moon summary fields renders Moon Summary table."""
        model = MoonPhaseOverviewModel(
            timestamp=750000000,
            datestamp="Fri, 08 Oct 1993 13:20:00 +0000",
            moon=MoonPhaseMoonSummaryModel(
                phase_name="Waning Crescent",
                emoji="\U0001f318",
                major_phase="Last Quarter",
                stage="waning",
                illumination="32%",
            ),
        )
        text = ReportGenerator(model).generate_report()
        assert "Waning Crescent" in text
        assert "Last Quarter" in text
        assert "32%" in text

    def test_model_with_sun_no_eclipse(self) -> None:
        """Sun info without eclipse should render Sun Info but no Solar Eclipse section."""
        model = MoonPhaseOverviewModel(
            timestamp=750000000,
            datestamp="Fri, 08 Oct 1993 13:20:00 +0000",
            moon=MoonPhaseMoonSummaryModel(),
            sun=MoonPhaseSunInfoModel(
                sunrise_timestamp="07:15",
                sunset_timestamp="18:18",
            ),
        )
        text = ReportGenerator(model).generate_report()
        assert "Sun Info" in text
        assert "07:15" in text
        assert "Next Solar Eclipse" not in text

    def test_model_with_location(self) -> None:
        """Location section renders when location is present."""
        model = MoonPhaseOverviewModel(
            timestamp=750000000,
            datestamp="Fri, 08 Oct 1993 13:20:00 +0000",
            moon=MoonPhaseMoonSummaryModel(),
            location=MoonPhaseLocationModel(
                latitude="51.50853",
                longitude="-0.12574",
                using_default_location=False,
            ),
        )
        text = ReportGenerator(model).generate_report()
        assert "Location" in text
        assert "51.50853" in text
        assert "-0.12574" in text
        assert "No" in text  # Default Location = No


# =====================================================================
# 5. TypeError for unsupported model
# =====================================================================


class TestMoonPhaseOverviewTypeError:
    """ReportGenerator rejects unsupported model types."""

    def test_unsupported_type_raises(self) -> None:
        with pytest.raises(TypeError, match="Unsupported model type"):
            ReportGenerator({"not": "a model"})  # type: ignore[arg-type]
