"""
Expected positions for house system G.

This file is auto-generated by scripts/regenerate_all.py
DO NOT EDIT MANUALLY - regenerate using: python scripts/regenerate_all.py --house-systems

Total entries: 0
"""

EXPECTED_POSITIONS = {}
