#!/usr/bin/env python3
"""Generate the chart-glyph <symbol> definitions in the SVG templates.

Builds all 80 glyph symbols from open, self-contained sources:

  * Symbola (George Douros)          -- public domain  -> classic signs/planets/
                                                          asteroids/Lilith/Priapus/Rx
  * Noto Sans Symbols 2 (Google)     -- SIL OFL 1.1    -> modern TNO / Uranian points
  * clean-room geometry (this file)  -- original       -> Sun/Earth/Uranus/Pluto/
                                                          Ixion, the lunar nodes,
                                                          White Moon / Interpolated
                                                          Perigee, aspects, Arabic
                                                          parts, Vertex/East Point/
                                                          Midpoint/star

Only the glyph outlines are derived from the fonts; the fonts themselves are never
redistributed (downloaded to a git-ignored cache at build time). Outlines are
normalised into the per-group coordinate box the templates already expect and the
existing `var(--kerykeion-chart-color-*)` style hooks are preserved, so themes and
the Python renderers keep working unchanged.

Every symbol the templates carry is declared in SPEC. That is load-bearing: the
block between the markers is rewritten wholesale, so anything absent from SPEC is
silently deleted on the next run. Five points (Interpolated Lilith, Mean/True
Priapus, White Moon, Interpolated Perigee) were in exactly that state and are now
declared here.

Run with:  uv run python scripts/build_chart_glyphs.py
Idempotent: rewrites the block between the GLYPHS:BEGIN / GLYPHS:END markers.
"""
from __future__ import annotations
import hashlib
import pathlib
import urllib.request
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "kerykeion" / "charts" / "templates"
TEMPLATE_FILES = ["chart.xml", "wheel_only.xml", "aspect_grid_only.xml", "modern_wheel.xml"]
CACHE = ROOT / "scripts" / ".glyph-cache"

FONT_SOURCES = {
    "Symbola": (
        "https://github.com/ChiefMikeK/ttf-symbola/raw/master/Symbola.ttf",
        "98c20d0c96bbee0cb8f125297bad388210e2e901fea89820697488ae0a57d688",
    ),
    "Noto2": (
        "https://github.com/notofonts/notofonts.github.io/raw/main/fonts/"
        "NotoSansSymbols2/unhinted/ttf/NotoSansSymbols2-Regular.ttf",
        "c4a0a80f0041ce4be81e2478faad22776d23edb98ae3f0d19bd37044820ecf9d",
    ),
}

BEGIN = "<!-- GLYPHS:BEGIN (generated by scripts/build_chart_glyphs.py — do not edit by hand) -->"
END = "<!-- GLYPHS:END -->"

# per-group coordinate box (matches the <use> transforms in the renderers)
BOX = {"sign": 32, "planet": 24, "point": 24, "aspect": 10, "retro": 12, "text": 24}


# --------------------------------------------------------------------------- fonts
def _sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def fetch_font(key: str) -> "Font":
    url, sha = FONT_SOURCES[key]
    CACHE.mkdir(parents=True, exist_ok=True)
    dest = CACHE / f"{key}.ttf"
    # Drop a corrupt cached copy (e.g. a download truncated by a dropped
    # connection or a captive-portal HTML page) so we re-fetch instead of
    # failing forever on a stale file.
    if dest.exists() and _sha256(dest) != sha:
        dest.unlink()
    if not dest.exists():
        if not url.startswith("https://"):
            raise ValueError(f"refusing non-HTTPS font URL for {key}: {url!r}")
        print(f"  downloading {key} …")
        tmp = dest.with_suffix(".ttf.part")
        urllib.request.urlretrieve(url, tmp)  # noqa: S310 - scheme checked above
        got = _sha256(tmp)
        if got != sha:
            tmp.unlink(missing_ok=True)
            raise SystemExit(
                f"sha256 mismatch for {key}: expected {sha}, got {got}. "
                "Download likely failed — re-run to retry."
            )
        tmp.replace(dest)  # atomic: only a verified file ever lands in the cache
    return Font(dest)


class Font:
    def __init__(self, path: pathlib.Path):
        self.ttf = TTFont(str(path))
        self.cmap = self.ttf.getBestCmap()
        self.gs = self.ttf.getGlyphSet()

    def outline(self, codepoints, box, css, pad_frac=0.08) -> str:
        cp = next((c for c in codepoints if c in self.cmap), None)
        if cp is None:
            raise KeyError(f"none of {[hex(c) for c in codepoints]} in font")
        name = self.cmap[cp]
        bp = BoundsPen(self.gs)
        self.gs[name].draw(bp)
        if not bp.bounds:
            raise ValueError(f"empty glyph for {name}")
        xmin, ymin, xmax, ymax = bp.bounds
        gw, gh = xmax - xmin, ymax - ymin
        pad = box * pad_frac
        s = (box - 2 * pad) / max(gw, gh)
        ox, oy = (box - gw * s) / 2, (box - gh * s) / 2
        sp = SVGPathPen(self.gs)
        self.gs[name].draw(sp)
        t = f"translate({ox:.3f},{oy:.3f}) scale({s:.5f},{-s:.5f}) translate({-xmin:.3f},{-ymax:.3f})"
        return f'<g transform="{t}"><path d="{sp.getCommands()}" style="fill: {css}"/></g>'


def V(name: str) -> str:
    return f"var(--kerykeion-chart-color-{name})"


# --------------------------------------------------------------------- weight
# One weight for every glyph, and it is not a taste call — it is measured.
#
# The font-derived silhouettes cannot be re-weighted: their stem is baked into
# the contour, so a stroke-width has nothing to act on and ink can only be added
# to a filled shape, never removed. They are therefore the fixed point, and the
# stroke artwork is tuned to *them*.
#
# Measured in the browser over all 45 silhouettes, each in its own units, with
# stem = 2*area/perimeter (exact for a ribbon of constant width):
#
#     stem / ink extent -> min 5.78%   median 7.41%   max 10.47%
#
# `outline()` below places that ink at INK_FRACTION of the box, so stroke
# artwork lands on the same apparent weight at STEM_FRACTION * INK_FRACTION *
# box. Before this, seven unrelated widths were in use (1.1 … 1.9) and the
# stroke family ran 1.35x heavier than the silhouettes — the Sun read bolder
# than the Moon, and the aspects, drawn in a 10-unit box, reached 16% of their
# own ink: more than twice the silhouettes.
INK_FRACTION = 0.84  # = 1 - 2 * outline()'s pad_frac
STEM_FRACTION = 0.0741  # measured median of the 45 font silhouettes


def stroke_for(box: int) -> float:
    """Stroke width that reads at the same weight as the silhouettes, in `box` units."""
    return round(box * INK_FRACTION * STEM_FRACTION, 3)


W_SIGN = stroke_for(BOX["sign"])  # 1.992
W_POINT = stroke_for(BOX["point"])  # 1.494 — planets, points
W_RETRO = stroke_for(BOX["retro"])  # 0.747
W_ASPECT = stroke_for(BOX["aspect"])  # 0.622


def sk(v, w=W_POINT):
    return f'fill="none" stroke="{V(v)}" stroke-width="{w}" stroke-linecap="round" stroke-linejoin="round"'


def ska(v, w=W_ASPECT):
    return sk(v, w)


# --------------------------------------------------------------------------- spec
# (id, group, kind, payload)
#   kind "S"/"N" -> font glyph: payload = (css_var_name, [codepoints])
#   kind "C"     -> clean-room: payload = key into CLEAN
#   kind "T"     -> kept text label: payload = key into TEXT
P, PT, S, A = "planet", "point", "sign", "aspect"
SPEC = [
    ("Sun", P, "C", "Sun"),
    ("Moon", P, "S", ("moon", [0x263D])),
    ("Mercury", P, "S", ("mercury", [0x263F])),
    ("Venus", P, "S", ("venus", [0x2640])),
    ("Mars", P, "S", ("mars", [0x2642])),
    ("Jupiter", P, "S", ("jupiter", [0x2643])),
    ("Saturn", P, "S", ("saturn", [0x2644])),
    ("Uranus", P, "C", "Uranus"),
    ("Neptune", P, "S", ("neptune", [0x2646])),
    ("Pluto", P, "C", "Pluto"),
    ("Chiron", P, "S", ("chiron", [0x26B7])),
    ("Mean_Lilith", PT, "S", ("mean-lilith", [0x26B8])),
    # Drawn, not traced: Symbola's U+260A/U+260B read as a blob at wheel sizes.
    ("Mean_North_Lunar_Node", PT, "C", "Mean_North_Lunar_Node"),
    ("True_North_Lunar_Node", PT, "C", "True_North_Lunar_Node"),
    ("Mean_South_Lunar_Node", PT, "C", "Mean_South_Lunar_Node"),
    ("True_South_Lunar_Node", PT, "C", "True_South_Lunar_Node"),
    ("Ascendant", "text", "T", "Ascendant"),
    ("Medium_Coeli", "text", "T", "Medium_Coeli"),
    ("Descendant", "text", "T", "Descendant"),
    ("Imum_Coeli", "text", "T", "Imum_Coeli"),
    ("Earth", PT, "C", "Earth"),
    ("Pholus", PT, "N", ("pholus", [0x2BDB])),
    ("Sedna", PT, "N", ("sedna", [0x2BF2])),
    ("Haumea", PT, "N", ("haumea", [0x1F77B])),
    ("Makemake", PT, "N", ("makemake", [0x1F77C])),
    ("Ixion", PT, "C", "Ixion"),
    ("Orcus", PT, "N", ("orcus", [0x1F77F])),
    ("Quaoar", PT, "N", ("quaoar", [0x1F77E])),
    ("Cupido", PT, "N", ("cupido", [0x2BE0])),
    ("Hades", PT, "N", ("hades", [0x2BE1])),
    ("Zeus", PT, "N", ("zeus", [0x2BE2])),
    ("Kronos", PT, "N", ("kronos", [0x2BE3])),
    ("Apollon", PT, "N", ("apollon", [0x2BE4])),
    ("Admetos", PT, "N", ("admetos", [0x2BE5])),
    ("Vulkanus", PT, "N", ("vulkanus", [0x2BE6])),
    ("Poseidon", PT, "N", ("poseidon", [0x2BE7])),
    ("FixedStar", PT, "C", "FixedStar"),
    ("Midpoint", PT, "C", "Midpoint"),
    ("Anti_Vertex", PT, "C", "Anti_Vertex"),
    ("Ceres", PT, "S", ("ceres", [0x26B3])),
    ("Pallas", PT, "S", ("pallas", [0x26B4])),
    ("Juno", PT, "S", ("juno", [0x26B5])),
    ("Vesta", PT, "S", ("vesta", [0x26B6])),
    ("Vertex", PT, "C", "Vertex"),
    ("True_Lilith", PT, "S", ("mean-lilith", [0x26B8])),
    # Priapus is Lilith's opposite point, so it is Lilith's glyph turned around.
    ("Interpolated_Lilith", PT, "S", ("mean-lilith", [0x26B8])),
    ("Mean_Priapus", PT, "R", ("mean-lilith", [0x26B8])),
    ("True_Priapus", PT, "R", ("mean-lilith", [0x26B8])),
    ("White_Moon", PT, "C", "White_Moon"),
    ("Interpolated_Perigee", PT, "C", "Interpolated_Perigee"),
    ("Eris", PT, "N", ("eris", [0x2BF0])),
    ("East_Point", PT, "C", "East_Point"),
    ("Pars_Fortunae", PT, "C", "Pars_Fortunae"),
    ("Pars_Spiritus", PT, "C", "Pars_Spiritus"),
    ("Pars_Amoris", PT, "C", "Pars_Amoris"),
    ("Pars_Fidei", PT, "C", "Pars_Fidei"),
    ("Ari", S, "S", ("zodiac-icon-0", [0x2648])),
    ("Tau", S, "S", ("zodiac-icon-1", [0x2649])),
    ("Gem", S, "S", ("zodiac-icon-2", [0x264A])),
    ("Can", S, "S", ("zodiac-icon-3", [0x264B])),
    ("Leo", S, "S", ("zodiac-icon-4", [0x264C])),
    ("Vir", S, "S", ("zodiac-icon-5", [0x264D])),
    ("Lib", S, "S", ("zodiac-icon-6", [0x264E])),
    ("Sco", S, "S", ("zodiac-icon-7", [0x264F])),
    ("Sag", S, "S", ("zodiac-icon-8", [0x2650])),
    ("Cap", S, "S", ("zodiac-icon-9", [0x2651])),
    ("Aqu", S, "S", ("zodiac-icon-10", [0x2652])),
    ("Pis", S, "S", ("zodiac-icon-11", [0x2653])),
    ("orb0", A, "C", "orb0"), ("orb30", A, "C", "orb30"), ("orb45", A, "C", "orb45"),
    ("orb60", A, "C", "orb60"), ("orb72", A, "C", "orb72"), ("orb90", A, "C", "orb90"),
    ("orb120", A, "C", "orb120"), ("orb135", A, "C", "orb135"), ("orb144", A, "C", "orb144"),
    ("orb150", A, "C", "orb150"), ("orb180", A, "C", "orb180"),
    ("retrograde", "retro", "S", ("paper-0", [0x211E])),
]

# --------------------------------------------------------------------------- clean-room
TEXT = {
    "Ascendant": '<text y="20" style="font-size: 22px; fill: var(--kerykeion-chart-color-first-house)">As</text>',
    "Medium_Coeli": '<text y="20" style="font-size: 20px; fill: var(--kerykeion-chart-color-tenth-house)">Mc</text>',
    "Descendant": '<text y="20" style="font-size: 22px; fill: var(--kerykeion-chart-color-seventh-house)">Ds</text>',
    "Imum_Coeli": '<text y="20" style="font-size: 22px; fill: var(--kerykeion-chart-color-fourth-house)">Ic</text>',
}

# ------------------------------------------------------------- lunar nodes
# An arc with a ring on each end. The rings are placed by DERIVATION, not by
# six hand-tuned numbers: a ring whose centre sits at (R + r) along the radius
# through the contact point is internally tangent to the arc there, so the two
# curves share a tangent and the stroke reads as one continuous line. Change R
# or RING and the joint stays closed.
_NODE_R = 6.4  # arc radius
_NODE_RING = 2.2  # ring radius
_NODE_CY = 11.65  # arc centre, y
_NODE_THETA = 145.0  # where the arc meets the rings, degrees from centre


def _lunar_node(colour: str, south: bool = False) -> str:
    import math

    rad = math.radians(_NODE_THETA)
    cos, sin = math.cos(rad), math.sin(rad)
    tx, ty = 12 + _NODE_R * cos, _NODE_CY + _NODE_R * sin  # tangency, left side
    rx, ry = 12 + (_NODE_R + _NODE_RING) * cos, _NODE_CY + (_NODE_R + _NODE_RING) * sin
    if south:  # mirror about the box's horizontal axis
        ty, ry = 24 - ty, 24 - ry
    sweep = 0 if south else 1
    pen = (
        f'fill="none" stroke="{V(colour)}" stroke-width="{W_POINT}" stroke-linecap="round"'
    )
    return (
        f'<path d="M{tx:.4f},{ty:.4f} A{_NODE_R},{_NODE_R} 0 1,{sweep} {24 - tx:.4f},{ty:.4f}" {pen}/>'
        f'<circle cx="{rx:.4f}" cy="{ry:.4f}" r="{_NODE_RING}" {pen}/>'
        f'<circle cx="{24 - rx:.4f}" cy="{ry:.4f}" r="{_NODE_RING}" {pen}/>'
    )


def _lilith_cross(colour: str, filled_centre: bool = False) -> str:
    """Circle over a cross — White Moon / Interpolated Perigee share this build."""
    dot = f'<circle cx="12" cy="7.5" r="1.6" fill="{V(colour)}"/>' if filled_centre else ""
    pen = f'fill="none" stroke="{V(colour)}" stroke-width="{W_POINT}" stroke-linecap="round"'
    return (
        f'<circle cx="12" cy="7.5" r="4.5" {pen}/>{dot}'
        f'<line x1="12" y1="12" x2="12" y2="21" {pen}/>'
        f'<line x1="7.5" y1="16.5" x2="16.5" y2="16.5" {pen}/>'
    )


CLEAN = {
    # planets / points (box 24, centre 12)
    "Sun": f'<circle cx="12" cy="12" r="9" {sk("sun")}/><circle cx="12" cy="12" r="1.9" fill="{V("sun")}"/>',
    "Mean_North_Lunar_Node": _lunar_node("mean-node"),
    "True_North_Lunar_Node": _lunar_node("true-node"),
    "Mean_South_Lunar_Node": _lunar_node("mean-node", south=True),
    "True_South_Lunar_Node": _lunar_node("true-node", south=True),
    "White_Moon": _lilith_cross("mean-lilith"),
    "Interpolated_Perigee": _lilith_cross("mean-lilith", filled_centre=True),
    "Earth": f'<circle cx="12" cy="12" r="8.5" {sk("earth")}/><line x1="12" y1="3.5" x2="12" y2="20.5" {sk("earth")}/><line x1="3.5" y1="12" x2="20.5" y2="12" {sk("earth")}/>',
    # Herschel "H": two serifed bars + cross-bar + central stem to a hollow globe
    "Uranus": (f'<line x1="6.5" y1="3" x2="6.5" y2="13.5" {sk("uranus")}/><line x1="17.5" y1="3" x2="17.5" y2="13.5" {sk("uranus")}/>'
               f'<line x1="4.6" y1="3" x2="8.4" y2="3" {sk("uranus")}/><line x1="15.6" y1="3" x2="19.4" y2="3" {sk("uranus")}/>'
               f'<line x1="4.6" y1="13.5" x2="8.4" y2="13.5" {sk("uranus")}/><line x1="15.6" y1="13.5" x2="19.4" y2="13.5" {sk("uranus")}/>'
               f'<line x1="6.5" y1="8.25" x2="17.5" y2="8.25" {sk("uranus")}/><line x1="12" y1="8.25" x2="12" y2="18" {sk("uranus")}/>'
               f'<circle cx="12" cy="20" r="2.1" {sk("uranus")}/>'),
    # astrological bowl: circle cradled in an upward crescent, over a cross
    "Pluto": (f'<circle cx="12" cy="6.8" r="3.8" {sk("pluto")}/>'
              f'<path d="M5.6,8 A6.4,6.4 0 0 0 18.4,8" {sk("pluto")}/>'
              f'<line x1="12" y1="14.4" x2="12" y2="21.5" {sk("pluto")}/><line x1="8.4" y1="18" x2="15.6" y2="18" {sk("pluto")}/>'),
    "Ixion": (f'<circle cx="12" cy="12" r="9" {sk("ixion")}/><line x1="6" y1="6" x2="18" y2="18" {sk("ixion")}/>'
              f'<line x1="18" y1="6" x2="6" y2="18" {sk("ixion")}/><line x1="12" y1="3" x2="12" y2="21" {sk("ixion")}/>'),
    "FixedStar": f'<path d="M12,3 L14.12,9.09 L20.56,9.22 L15.42,13.11 L17.29,19.28 L12,15.6 L6.71,19.28 L8.58,13.11 L3.44,9.22 L9.88,9.09 Z" fill="{V("fixed-star-default, #d4a053")}"/>',
    "Midpoint": (f'<line x1="5" y1="12" x2="19" y2="12" stroke="{V("midpoint-default, #b58bff")}" stroke-width="{W_POINT}"/>'
                 f'<circle cx="5" cy="12" r="2.2" fill="{V("midpoint-default, #b58bff")}"/>'
                 f'<circle cx="19" cy="12" r="2.2" fill="{V("midpoint-default, #b58bff")}"/>'
                 f'<circle cx="12" cy="12" r="2.2" fill="{V("midpoint-default, #b58bff")}"/>'),
    "Vertex": f'<text x="12" y="16.5" text-anchor="middle" style="font-size:13px; fill: {V("vertex")}">Vx</text>',
    "Anti_Vertex": f'<text x="12" y="16.5" text-anchor="middle" style="font-size:13px; fill: {V("anti-vertex")}">Av</text>',
    "East_Point": (f'<circle cx="9" cy="12" r="6" {sk("ceres")}/><line x1="9" y1="6.2" x2="9" y2="17.8" {sk("ceres")}/>'
                   f'<line x1="3.2" y1="12" x2="14.8" y2="12" {sk("ceres")}/><line x1="14.8" y1="12" x2="19" y2="7.6" {sk("ceres")}/>'
                   f'<line x1="14.8" y1="12" x2="19" y2="16.4" {sk("ceres")}/>'),
    "Pars_Fortunae": f'<circle cx="12" cy="12" r="9" {sk("pars-fortunae")}/><line x1="5.6" y1="5.6" x2="18.4" y2="18.4" {sk("pars-fortunae")}/><line x1="18.4" y1="5.6" x2="5.6" y2="18.4" {sk("pars-fortunae")}/>',
    "Pars_Spiritus": (f'<circle cx="12" cy="12" r="9" {sk("pars-spiritus")}/><line x1="12" y1="6.5" x2="12" y2="17.5" {sk("pars-spiritus")}/>'
                      f'<line x1="6.5" y1="12" x2="17.5" y2="12" {sk("pars-spiritus")}/><line x1="8.1" y1="8.1" x2="15.9" y2="15.9" {sk("pars-spiritus")}/>'
                      f'<line x1="15.9" y1="8.1" x2="8.1" y2="15.9" {sk("pars-spiritus")}/>'),
    "Pars_Amoris": f'<circle cx="12" cy="12" r="9" {sk("pars-amoris")}/><path d="M12,16.5 C8.8,13.5 7.8,11.4 9.4,9.8 C10.5,8.7 12,9.3 12,10.6 C12,9.3 13.5,8.7 14.6,9.8 C16.2,11.4 15.2,13.5 12,16.5 Z" fill="{V("pars-amoris")}"/>',
    "Pars_Fidei": (f'<circle cx="12" cy="12" r="9" {sk("pars-fidei")}/><line x1="6.8" y1="12" x2="17.2" y2="12" {sk("pars-fidei")}/>'
                   f'<line x1="12" y1="6.8" x2="12" y2="17.2" {sk("pars-fidei")}/><line x1="8.4" y1="8.4" x2="15.6" y2="15.6" {sk("pars-fidei")}/>'),
    # aspects (box 10, centre 5)
    "orb0": f'<circle cx="4" cy="6" r="2.6" {ska("conjunction")}/><line x1="5.9" y1="4.1" x2="9" y2="1.2" {ska("conjunction")}/>',
    "orb30": f'<line x1="1" y1="5.6" x2="9" y2="5.6" {ska("semi-sextile")}/><path d="M1.6,1 L5,5.6 L8.4,1" {ska("semi-sextile")}/>',
    "orb45": f'<path d="M1.4,8.8 L8.8,8.8 M1.4,8.8 L5.1,1.4" {ska("semi-square")}/>',
    "orb60": f'<path d="M1.3,1.3 L8.7,8.7 M1.3,8.7 L8.7,1.3 M1,5 L9,5" {ska("sextile")}/>',
    "orb72": f'<circle cx="4.4" cy="4.4" r="2.9" {ska("quintile")}/><line x1="6.4" y1="6.4" x2="9.2" y2="9.2" {ska("quintile")}/>',
    "orb90": f'<rect x="1.3" y="1.3" width="7.4" height="7.4" {ska("square")}/>',
    "orb120": f'<path d="M5,1.2 L9,9 L1,9 Z" {ska("trine")}/>',
    "orb135": f'<rect x="1" y="1" width="5.3" height="5.3" {ska("sesquiquadrate")}/><path d="M4.4,9.4 L9.4,9.4 M9.4,9.4 L9.4,4.4" {ska("sesquiquadrate")}/>',
    "orb144": f'<circle cx="5" cy="4.5" r="2.8" {ska("biquintile")}/><line x1="3.2" y1="6.5" x2="1.1" y2="9.2" {ska("biquintile")}/><line x1="6.8" y1="6.5" x2="8.9" y2="9.2" {ska("biquintile")}/>',
    "orb150": f'<line x1="1" y1="4.4" x2="9" y2="4.4" {ska("quincunx")}/><path d="M1.6,9 L5,4.4 L8.4,9" {ska("quincunx")}/>',
    "orb180": f'<circle cx="3" cy="3" r="1.9" {ska("opposition")}/><circle cx="7" cy="7" r="1.9" {ska("opposition")}/><line x1="4.35" y1="4.35" x2="5.65" y2="5.65" {ska("opposition")}/>',
    # retrograde clean-room fallback (box 12) — used by build_lines() only if
    # Symbola ever loses U+211E (the "S" font glyph is the normal path)
    "retrograde": f'<path d="M3,11.2 L3,1.2 L6.2,1.2 C8.4,1.2 8.4,5.4 6.2,5.4 L3,5.4 M5.6,5.4 L9.2,11.2" fill="none" stroke="{V("paper-0")}" stroke-width="{W_RETRO}" stroke-linecap="round" stroke-linejoin="round"/>',
}

SECTION = {  # printed as a comment before this id
    "Sun": "Planets", "Ascendant": "Angles", "Earth": "Points",
    "Ari": "Signs", "orb0": "Aspects", "retrograde": "Retrograde",
}


def build_lines() -> list[str]:
    """Return the block as a list of un-indented lines (markers + <symbol> defs)."""
    fonts = {"S": fetch_font("Symbola"), "N": fetch_font("Noto2")}
    lines = [BEGIN]
    for sid, group, kind, payload in SPEC:
        if sid in SECTION:
            lines.append(f"<!-- {SECTION[sid]} -->")
        box = BOX[group]
        if kind in ("S", "N", "R"):
            varname, cps = payload
            try:
                inner = fonts["S" if kind == "R" else kind].outline(cps, box, V(varname))
                if kind == "R":  # opposite point -> the same glyph, turned around
                    inner = f'<g transform="rotate(180 {box / 2:g} {box / 2:g})">{inner}</g>'
            except (KeyError, ValueError):
                # font no longer carries the codepoint -> fall back to clean-room
                if sid not in CLEAN:
                    raise
                inner = CLEAN[sid]
        elif kind == "C":
            inner = CLEAN[payload]
        else:  # T
            inner = TEXT[payload]
        lines += [f'<symbol id="{sid}">', f"    {inner}", "</symbol>"]
    lines.append(END)
    return lines


def splice(text: str, lines: list[str]) -> str:
    """Replace the existing symbol defs (or the marker block) with the new lines."""
    if BEGIN in text and END in text:
        b, e = text.index(BEGIN), text.index(END) + len(END)
    else:  # first run: span from the first <symbol> to the last </symbol>
        b, e = text.index("<symbol"), text.rindex("</symbol>") + len("</symbol>")
    line_start = text.rfind("\n", 0, b) + 1
    indent = text[line_start:b]
    block = ("\n" + indent).join(lines)
    return text[:line_start] + indent + block + text[e:]


def main():
    print("Building chart glyphs (Symbola PD + Noto Sans Symbols 2 OFL + clean-room)…")
    lines = build_lines()
    for fn in TEMPLATE_FILES:
        p = TEMPLATES / fn
        p.write_text(splice(p.read_text(encoding="utf-8"), lines), encoding="utf-8")
        print(f"  updated {fn}")
    counts = {"S": "Symbola", "N": "Noto2", "C": "clean-room", "T": "text"}
    tally = {k: sum(1 for s in SPEC if s[2] == k) for k in counts}
    print("done — " + "  ".join(f"{counts[k]}:{tally[k]}" for k in counts))


if __name__ == "__main__":
    main()
