"""
Configuration-specific test fixtures for Kerykeion.

This package contains expected data for various Kerykeion configurations:
- house_systems/: Expected positions for each house system (Koch, Placidus, Whole Sign, etc.)
- sidereal_modes/: Expected positions for each sidereal mode (Lahiri, Fagan-Bradley, etc.)
- perspectives/: Expected positions for each perspective type (Heliocentric, Topocentric, etc.)
- returns/: Expected data for Solar and Lunar returns
- composite/: Expected data for composite charts
- ephemeris/: Expected ephemeris data for time ranges

All files are auto-generated by scripts/regenerate_all.py with the appropriate flags.
"""

from pathlib import Path

CONFIGURATIONS_DIR = Path(__file__).parent

# Subdirectory paths
HOUSE_SYSTEMS_DIR = CONFIGURATIONS_DIR / "house_systems"
SIDEREAL_MODES_DIR = CONFIGURATIONS_DIR / "sidereal_modes"
PERSPECTIVES_DIR = CONFIGURATIONS_DIR / "perspectives"
RETURNS_DIR = CONFIGURATIONS_DIR / "returns"
COMPOSITE_DIR = CONFIGURATIONS_DIR / "composite"
EPHEMERIS_DIR = CONFIGURATIONS_DIR / "ephemeris"
