name: Test all changes 💫

on:
  push:

jobs:
  build-n-publish:
    name: Test all changes 💫
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install pipenv
        run: >-
          python -m
          pip install
          pipenv
          --user
      - name: Run the test
        run: >-
          pipenv
          run
          test
